import 'dart:math' as math;

import 'package:flutter/material.dart';

import 'package:forui/forui.dart';
import 'package:intl/intl.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FTheme.neutral.light.touch.color,
///  style: FTheme.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FTheme.neutral.light.touch.color,
///    style: FTheme.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FCalendarStyle calendarStyle({
  required FColors colors,
  required FTypography typography,
  required FIcons icons,
  required FStyle style,
  required FHapticFeedback hapticFeedback,
  required bool touch,
  Size? daySize,
}) => FCalendarStyle(
  headerStyle: .inherit(
    colors: colors,
    typography: typography,
    icons: icons,
    style: style,
    touch: touch,
  ),
  dayPickerStyle: FCalendarDayPickerStyle.inherit(
    colors: colors,
    typography: typography,
    style: style,
    touch: touch,
  ).copyWith(
    daySize: daySize,
    headerSpacing: 12,
    daySpacing: 6,
    dayStyles: _dayStyles(colors: colors, typography: typography, style: style),
  ),
  monthPickerStyle: .inherit(
    colors: colors,
    typography: typography,
    style: style,
  ),
  yearPickerStyle: .inherit(
    colors: colors,
    typography: typography,
    style: style,
  ),
  wheelPickerStyle: .inherit(
    colors: colors,
    style: style,
    typography: typography,
    hapticFeedback: hapticFeedback,
    touch: touch,
  ),
  decoration: const BoxDecoration(),
  padding: EdgeInsets.zero,
);

/// Current-month days sit on a muted tile, adjacent-month days stay bare, and
/// the selected day fills with the foreground colour.
///
/// Forui's inherited styles carry a separate entry per interaction combination
/// (`today & pressed`, `adjacent & focused`, ...), and `resolve` prefers the
/// most specific match. Overriding only the plain constraints would leave those
/// compounds showing the inherited look on tap or focus, so each rule is
/// applied with `match`, which sweeps every entry containing the variant.
/// The interaction variants Forui pairs with each day state. They are included
/// when matching so a rule also covers its `& hovered`, `& pressed` and
/// `& focused` entries, which `match` skips unless the variant is present.
final _interactions = <FCalendarDayVariant>{
  FCalendarDayVariant.hovered,
  FCalendarDayVariant.pressed,
  FCalendarDayVariant.focused,
};

FCalendarDayStyles _dayStyles({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) {
  final tile = RoundedSuperellipseBorder(borderRadius: style.borderRadius.md);
  final muted = FCalendarDayStyleDelta.delta(
    foreground: .shapeDelta(color: colors.muted, shape: tile),
  );
  final filled = FCalendarDayStyleDelta.delta(
    textStyle: .delta(color: colors.background),
    foreground: .shapeDelta(color: colors.foreground, shape: tile),
  );

  return FCalendarDayStyles(
    FCalendarDayStyles.inherit(
      colors: colors,
      typography: typography,
      style: style,
    ).apply([
      // The circled number replaces Forui's underline as today's marker.
      .variants(.delta(textStyle: .delta(decoration: () => TextDecoration.none))),
      .base(muted),
      .variants(muted),
      .match({.adjacent, ..._interactions}, .delta(
        textStyle: .delta(color: colors.mutedForeground),
        foreground: .shapeDelta(color: Colors.transparent, shape: tile),
      )),
      .match({.disabled, ..._interactions}, .delta(
        textStyle: .delta(color: colors.disable(colors.mutedForeground)),
        foreground: .shapeDelta(color: colors.muted, shape: tile),
      )),
      // `match` cannot target `single` alone -- widening the set to reach its
      // compounds would also sweep the bare interaction entries -- so the
      // selected combinations are set explicitly.
      .exact({
        .single,
        .single.and(.today),
        for (final i in _interactions) ...[.single.and(i), .single.and(.today).and(i)],
      }, filled),
    ]),
  );
}

/// Builds a day tile. Days in [eventDates] are outlined, and today's number
/// sits in a filled circle.
///
/// The grid lays cells out edge to edge horizontally, so [gap] is applied by
/// insetting the tile within its cell rather than by the grid.
FCalendarDayBuilder dayBuilder({
  required FColors colors,
  required FStyle style,
  required Set<DateTime> eventDates,
  required Size daySize,
  double gap = 6,
}) => (context, styles, localizations, date, variants) {
  final day = styles.resolve(variants);
  final label = Text(
    DateFormat.d(localizations.localeName).format(date),
    style: day.textStyle,
  );
  final adjacent = variants.contains(FCalendarDayVariant.adjacent);
  final selected = variants.contains(FCalendarDayVariant.single);
  final today = variants.contains(FCalendarDayVariant.today);

  // Skipped when selected: that tile is already filled and would clash.
  final child = today && !selected
      ? DecoratedBox(
          decoration: BoxDecoration(color: colors.foreground, shape: .circle),
          child: SizedBox.square(
            // Sized off the cell so the circle keeps its proportions on any
            // layout, with room for the tile inset.
            dimension: math.min(daySize.height, daySize.width - gap) * 0.7,
            // The label keeps the shared text style so the number does not
            // change size when the circle appears or is replaced by selection.
            child: Center(
              child: Text(
                DateFormat.d(localizations.localeName).format(date),
                style: day.textStyle.copyWith(color: colors.background),
              ),
            ),
          ),
        )
      : label;

  final hasEvent = !adjacent && eventDates.contains(DateUtils.dateOnly(date));

  return Padding(
    padding: EdgeInsets.symmetric(horizontal: gap / 2),
    child: DecoratedBox(
      decoration: day.background,
      child: DecoratedBox(
        decoration: day.foreground,
        child: DecoratedBox(
          decoration: hasEvent
              ? ShapeDecoration(
                  shape: RoundedSuperellipseBorder(
                    side: BorderSide(color: colors.foreground),
                    borderRadius: style.borderRadius.md,
                  ),
                )
              : const BoxDecoration(),
          child: Center(child: child),
        ),
      ),
    ),
  );
};
