import 'package:flutter/material.dart';

import 'package:forui/forui.dart';
import 'package:intl/intl.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FTheme.neutral.light.touch.color,
///  style: FTheme.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FTheme.neutral.light.touch.color,
///    style: FTheme.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FCalendarStyle calendarStyle({
  required FColors colors,
  required FTypography typography,
  required FIcons icons,
  required FStyle style,
  required FHapticFeedback hapticFeedback,
  required bool touch,
  Size? daySize,
}) => FCalendarStyle(
  headerStyle: .inherit(
    colors: colors,
    typography: typography,
    icons: icons,
    style: style,
    touch: touch,
  ),
  dayPickerStyle: FCalendarDayPickerStyle.inherit(
    colors: colors,
    typography: typography,
    style: style,
    touch: touch,
  ).copyWith(
    daySize: daySize,
    headerSpacing: 12,
    daySpacing: 6,
    dayStyles: _dayStyles(colors: colors, typography: typography, style: style),
  ),
  monthPickerStyle: .inherit(
    colors: colors,
    typography: typography,
    style: style,
  ),
  yearPickerStyle: .inherit(
    colors: colors,
    typography: typography,
    style: style,
  ),
  wheelPickerStyle: .inherit(
    colors: colors,
    style: style,
    typography: typography,
    hapticFeedback: hapticFeedback,
    touch: touch,
  ),
  decoration: const BoxDecoration(),
  padding: EdgeInsets.zero,
);

/// Current-month days sit on a muted tile, adjacent-month days stay bare, and
/// the selected day fills with the foreground colour.
FCalendarDayStyles _dayStyles({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) {
  final tile = RoundedSuperellipseBorder(borderRadius: style.borderRadius.md);

  return FCalendarDayStyles(
    FCalendarDayStyles.inherit(
      colors: colors,
      typography: typography,
      style: style,
    ).apply([
      .base(.delta(foreground: .shapeDelta(color: colors.muted, shape: tile))),
      // The inherited `today` variant carries its own foreground, so the
      // fill has to be set explicitly rather than inherited from the base.
      .exact({.today}, .delta(
        textStyle: .delta(decoration: () => TextDecoration.none),
        foreground: .shapeDelta(color: colors.muted, shape: tile),
      )),
      .exact({.adjacent}, .delta(
        textStyle: .delta(color: colors.mutedForeground),
        foreground: .shapeDelta(color: Colors.transparent, shape: tile),
      )),
      .exact({.single}, .delta(
        textStyle: .delta(color: colors.background),
        foreground: .shapeDelta(color: colors.foreground, shape: tile),
      )),
      .exact({.single.and(.today)}, .delta(
        textStyle: .delta(color: colors.background),
        foreground: .shapeDelta(color: colors.foreground, shape: tile),
      )),
    ]),
  );
}

/// Builds a day tile. Days in [eventDates] are outlined, and today's number
/// sits in a filled circle.
///
/// The grid lays cells out edge to edge horizontally, so [gap] is applied by
/// insetting the tile within its cell rather than by the grid.
FCalendarDayBuilder dayBuilder({
  required FColors colors,
  required FStyle style,
  required Set<DateTime> eventDates,
  double gap = 6,
}) => (context, styles, localizations, date, variants) {
  final day = styles.resolve(variants);
  final label = Text(
    DateFormat.d(localizations.localeName).format(date),
    style: day.textStyle,
  );
  final adjacent = variants.contains(FCalendarDayVariant.adjacent);
  final selected = variants.contains(FCalendarDayVariant.single);
  final today = variants.contains(FCalendarDayVariant.today);

  // Skipped when selected: that tile is already filled and would clash.
  final child = today && !selected
      ? DecoratedBox(
          decoration: BoxDecoration(color: colors.foreground, shape: .circle),
          child: SizedBox.square(
            dimension: 28,
            child: Center(
              child: Text(
                DateFormat.d(localizations.localeName).format(date),
                style: day.textStyle.copyWith(color: colors.background),
              ),
            ),
          ),
        )
      : label;

  final hasEvent = !adjacent && eventDates.contains(DateUtils.dateOnly(date));

  return Padding(
    padding: EdgeInsets.symmetric(horizontal: gap / 2),
    child: DecoratedBox(
      decoration: day.background,
      child: DecoratedBox(
        decoration: day.foreground,
        child: DecoratedBox(
          decoration: hasEvent
              ? ShapeDecoration(
                  shape: RoundedSuperellipseBorder(
                    side: BorderSide(color: colors.foreground),
                    borderRadius: style.borderRadius.md,
                  ),
                )
              : const BoxDecoration(),
          child: Center(child: child),
        ),
      ),
    ),
  );
};
