import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FTheme.neutral.light.touch.color,
///  style: FTheme.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FTheme.neutral.light.touch.color,
///    style: FTheme.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FLineCalendarStyle lineCalendarStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) {
  final focusedShape = RoundedSuperellipseBorder(
    side: BorderSide(color: colors.primary, width: style.borderWidth),
    borderRadius: style.borderRadius.md,
  );
  return .new(
    decoration: FVariants.from(
      ShapeDecoration(
        shape: RoundedSuperellipseBorder(borderRadius: style.borderRadius.md),
        color: colors.card,
      ),
      variants: {
        [.focused]: .shapeDelta(shape: focusedShape),
        [.hovered, .pressed]: .shapeDelta(color: colors.secondary),
        [.hovered.and(.focused), .pressed.and(.focused)]: .shapeDelta(
          color: colors.secondary,
          shape: focusedShape,
        ),
        [.disabled]: .shapeDelta(color: colors.disable(colors.card)),
        [.disabled.and(.focused)]: .shapeDelta(
          color: colors.disable(colors.card),
          shape: focusedShape,
        ),
        [.disabled.and(.selected).and(.focused)]: .shapeDelta(
          shape: focusedShape,
          color: colors.disable(colors.primary),
        ),
        [.selected]: .shapeDelta(
          shape: RoundedSuperellipseBorder(borderRadius: style.borderRadius.md),
          color: colors.primary,
        ),
        [.selected.and(.focused)]: .shapeDelta(
          color: colors.primary,
          shape: focusedShape,
        ),
        [.selected.and(.hovered), .selected.and(.pressed)]: .shapeDelta(
          shape: RoundedSuperellipseBorder(borderRadius: style.borderRadius.md),
          color: colors.hover(colors.primary),
        ),
        [
          .selected.and(.hovered).and(.focused),
          .selected.and(.pressed).and(.focused),
        ]: .shapeDelta(
          shape: focusedShape,
          color: colors.hover(colors.primary),
        ),
        [.selected.and(.disabled)]: .shapeDelta(
          color: colors.disable(colors.primary),
        ),
        [.today]: .shapeDelta(color: colors.secondary),
        [.today.and(.focused)]: .shapeDelta(
          color: colors.secondary,
          shape: focusedShape,
        ),
        [.today.and(.hovered), .today.and(.pressed)]: .shapeDelta(
          color: colors.hover(colors.secondary),
        ),
        [
          .today.and(.hovered).and(.focused),
          .today.and(.pressed).and(.focused),
        ]: .shapeDelta(
          color: colors.hover(colors.secondary),
          shape: focusedShape,
        ),
      },
    ),
    todayIndicatorColor: FVariants(
      colors.foreground,
      variants: {
        [.hovered, .pressed]: colors.hover(colors.foreground),
        [.disabled]: colors.disable(colors.foreground),
        [.selected]: colors.primaryForeground,
        [.selected.and(.hovered), .selected.and(.pressed)]: colors.hover(
          colors.primaryForeground,
        ),
        [.selected.and(.disabled)]: colors.disable(colors.primaryForeground),
      },
    ),
    dateTextStyle: FVariants.from(
      typography.body.sm.copyWith(color: colors.foreground, height: 1),
      variants: {
        [.disabled]: .delta(color: colors.disable(colors.foreground)),
        [.selected]: .delta(color: colors.primaryForeground),
        [.selected.and(.disabled)]: .delta(
          color: colors.disable(colors.primaryForeground),
        ),
      },
    ),
    weekdayTextStyle: FVariants.from(
      typography.body.xs3.copyWith(color: colors.mutedForeground, height: 1),
      variants: {
        [.disabled]: .delta(color: colors.disable(colors.mutedForeground)),
        [.selected]: .delta(color: colors.primaryForeground),
        [.selected.and(.disabled)]: .delta(
          color: colors.disable(colors.primaryForeground),
        ),
      },
    ),
    tappableStyle: style.tappableStyle,
  );
}
