import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FTheme.neutral.light.touch.color,
///  style: FTheme.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FTheme.neutral.light.touch.color,
///    style: FTheme.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FTabsStyle tabsStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FTabsStyle(
  decoration: ShapeDecoration(
    shape: RoundedSuperellipseBorder(
      side: BorderSide(color: colors.muted, width: style.borderWidth),
      borderRadius: style.borderRadius.md,
    ),
    color: colors.muted,
  ),
  labelTextStyle: FVariants.from(
    typography.body.sm.copyWith(
      fontWeight: .w500,
      color: colors.mutedForeground,
    ),
    variants: {
      [.selected]: .delta(color: colors.foreground),
    },
  ),
  indicatorDecoration: ShapeDecoration(
    shape: RoundedSuperellipseBorder(borderRadius: style.borderRadius.md),
    color: colors.background,
  ),
  focusedOutlineStyle: style.focusedOutlineStyle,
  padding: const .all(4),
  indicatorSize: .tab,
  minHeight: 36,
  spacing: 10,
);

/// An underline variant of [tabsStyle], matching a Material-style tab bar:
/// no container background, the selected tab marked by a bar under its label.
FTabsStyle underlineTabsStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FTabsStyle(
  decoration: BoxDecoration(
    border: Border(
      bottom: BorderSide(color: colors.border, width: style.borderWidth),
    ),
  ),
  labelTextStyle: FVariants.from(
    typography.body.sm.copyWith(
      fontWeight: .w500,
      color: colors.mutedForeground,
    ),
    variants: {
      [.selected]: .delta(color: colors.primary, fontWeight: .w600),
    },
  ),
  indicatorDecoration: BoxDecoration(
    border: Border(bottom: BorderSide(color: colors.primary, width: 2)),
  ),
  focusedOutlineStyle: style.focusedOutlineStyle,
  padding: EdgeInsets.zero,
  indicatorSize: .tab,
  minHeight: 44,
  spacing: 0,
);
